# Generated by Django 4.0.1 on 2022-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='islikedbycurrentuser',
            field=models.BooleanField(default=False),
        ),
    ]
